id: AA0C8E08A
title: CIV_XVII. 9 Illustrations of the Buddha’s Acts
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.966521
  last_modified_at: 2022-03-01 23:02:41.966526
