id: AA0C8E08A
title: CII_XII. General Characteristics of the Reality Free from Pollutions
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.954073
  last_modified_at: 2022-03-01 23:02:41.954079
