id: AA0C8E08A
title: CI_V. The Three Jewels as Refuges
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.992482
  last_modified_at: 2022-03-01 23:02:41.992486
