id: AA0C8E08A
title: CI_VIII. Analysis of the Germ from 10 Points of View
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:42.009420
  last_modified_at: 2022-03-01 23:02:42.009426
