id: AA0C8E08A
title: CIV_XVI. General Characteristics of the Acts of the Buddha
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.962769
  last_modified_at: 2022-03-01 23:02:41.962773
