id: AA0C8E08A
title: 'CI_VII. The Sermon: All Living Beings are possessed of The Matrix of the Tathāgata'
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.996817
  last_modified_at: 2022-03-01 23:02:41.996820
