id: AA0C8E08A
title: CI_IX. The 9 Illustrations on the Germ Covered with Defilements
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.988736
  last_modified_at: 2022-03-01 23:02:41.988743
