id: AA0C8E08A
title: CII_XIII. 8 Points on the Undefiled Reality
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.960124
  last_modified_at: 2022-03-01 23:02:41.960133
