id: AA0C8E08A
title: CIII_XV. 64 Properties of the Buddha
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.951506
  last_modified_at: 2022-03-01 23:02:41.951511
