id: AA0C8E08A
title: CI_VI. The Germ Of Three Jewels In Four Aspects
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.994998
  last_modified_at: 2022-03-01 23:02:41.995001
