id: AA0C8E08A
title: CI_III. The Jewel of the Doctrine
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.978999
  last_modified_at: 2022-03-01 23:02:41.979002
