id: AA0C8E08A
title: CIII_XIV. General Characteristics Of The Buddha’s Properties
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.948154
  last_modified_at: 2022-03-01 23:02:41.948160
