id: AA0C8E08A
title: CI_X. The Essential Characteristics of the Matrix of the TathÄgata
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:42.014004
  last_modified_at: 2022-03-01 23:02:42.014008
