id: AA0C8E08A
title: CV_XVIII. The Merits of Having Faith in the Doctrine of the Essence of Buddhahood
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:42.017703
  last_modified_at: 2022-03-01 23:02:42.017706
