id: AA0C8E08A
title: CI_IV. The Jewel of the Community
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:02:41.982089
  last_modified_at: 2022-03-01 23:02:41.982092
